# Generated by Django 6.0.4 on 2026-05-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_poster_url_alter_movie_imdb_rate_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='movie',
            name='movies_movi_imdb_ra_1cb01b_idx',
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title', '-imdb_rate'], name='movies_movi_title_cf7378_idx'),
        ),
    ]
